### ISSUE TITLE
对于ASN变量

### ISSUE THREAD

**Issue by Jeromeliaya** [cmliu/CloudFlareIPlus#1]
CM博主你好，请问是否可以修改ASN变量来扫描不同ASN的cdnIP，然后再继续进行后续操作

**Comment by cmliu** [comment]
该脚本没有验证的功能，只有跑CF对应的ASN时才有意义

**Comment by cmliu** [comment]
> CM博主你好，请问是否可以修改ASN变量来扫描不同ASN的cdnIP，然后再继续进行后续操作

该脚本没有验证的功能，只有跑CF对应的ASN时才有意义
